# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "glove80_lh", "glove80_rh" ]

include:
  - board: seeeduino_xiao_ble
    shield: glove80_dongle prospector_adapter
    cmake-args: -DCONFIG_EXPERIMENTAL_RGB_LAYER=n -DCONFIG_ZMK_RGB_UNDERGLOW=n -DCONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n -DCONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80 -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2 -DCONFIG_BT_MAX_CONN=6 -DCONFIG_BT_MAX_PAIRED=6

  - board: glove80_lh
    cmake-args: -DCONFIG_EXPERIMENTAL_RGB_LAYER=y -DCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y -DCONFIG_ZMK_POINTING=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_HID_INDICATORS=y -DCONFIG_ZMK_BLE=y -DCONFIG_ZMK_RGB_UNDERGLOW_FORCE_CENTRAL_SOURCES=y

  - board: glove80_rh
    cmake-args: -DCONFIG_EXPERIMENTAL_RGB_LAYER=y -DCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y -DCONFIG_ZMK_POINTING=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_HID_INDICATORS=y -DCONFIG_ZMK_BLE=y

  - board: glove80_lh
    shield: settings_reset
    cmake-args: -DCONFIG_BT_MAX_PAIRED=0 -DCONFIG_EXPERIMENTAL_RGB_LAYER=n -DCONFIG_ZMK_RGB_UNDERGLOW=n -DCONFIG_ZMK_SPLIT=n

  - board: glove80_rh
    shield: settings_reset
    cmake-args: -DCONFIG_BT_MAX_PAIRED=0 -DCONFIG_EXPERIMENTAL_RGB_LAYER=n -DCONFIG_ZMK_RGB_UNDERGLOW=n -DCONFIG_ZMK_SPLIT=n

  - board: seeeduino_xiao_ble
    shield: settings_reset
    cmake-args: -DCONFIG_BT_MAX_PAIRED=0 -DCONFIG_EXPERIMENTAL_RGB_LAYER=n -DCONFIG_ZMK_RGB_UNDERGLOW=n -DCONFIG_ZMK_SPLIT=n
