	//
	// USE_NUMPAD_KEYCODES puts `KP_*` keycodes into the Number layer.
	//
#ifdef USE_NUMPAD_KEYCODES
	#define _KP_N0 KP_N0
	#define _KP_N1 KP_N1
	#define _KP_N2 KP_N2
	#define _KP_N3 KP_N3
	#define _KP_N4 KP_N4
	#define _KP_N5 KP_N5
	#define _KP_N6 KP_N6
	#define _KP_N7 KP_N7
	#define _KP_N8 KP_N8
	#define _KP_N9 KP_N9
	#define _KP_PLUS KP_PLUS
	#define _KP_MINUS KP_MINUS
	#define _KP_ASTERISK KP_ASTERISK
	#define _KP_SLASH KP_SLASH
	#define _KP_COMMA KP_COMMA
	#define _KP_DOT KP_DOT
	#define _KP_EQUAL KP_EQUAL
	#define _KP_ENTER KP_ENTER
#else
	#define _KP_N0 N0
	#define _KP_N1 N1
	#define _KP_N2 N2
	#define _KP_N3 N3
	#define _KP_N4 N4
	#define _KP_N5 N5
	#define _KP_N6 N6
	#define _KP_N7 N7
	#define _KP_N8 N8
	#define _KP_N9 N9
	#define _KP_PLUS PLUS
	#define _KP_MINUS MINUS
	#define _KP_ASTERISK ASTERISK
	#define _KP_SLASH SLASH
	#define _KP_COMMA COMMA
	#define _KP_DOT DOT
	#define _KP_EQUAL EQUAL
	#define _KP_ENTER ENTER
#endif
	
	//
	// Keymap specific knowledge of the base layer's alpha + ZMK layout
	//
#if defined(LAYER_Enthium) && LAYER_Enthium == 0
	#define KEY_LH_C6R1 HOME
	#define KEY_LH_C5R1 END
	#define KEY_LH_C4R1 A
	#define KEY_LH_C3R1 B
	#define KEY_LH_C2R1 C
	#define KEY_RH_C2R1 D
	#define KEY_RH_C3R1 E
	#define KEY_RH_C4R1 F
	#define KEY_RH_C5R1 LEFT
	#define KEY_RH_C6R1 RIGHT
	#define KEY_LH_C6R2 PG_UP
	#define KEY_LH_C5R2 N1
	#define KEY_LH_C4R2 N2
	#define KEY_LH_C3R2 N3
	#define KEY_LH_C2R2 N4
	#define KEY_LH_C1R2 N5
	#define KEY_RH_C1R2 N6
	#define KEY_RH_C2R2 N7
	#define KEY_RH_C3R2 N8
	#define KEY_RH_C4R2 N9
	#define KEY_RH_C5R2 N0
	#define KEY_RH_C6R2 UP
	#define KEY_LH_C6R3 PG_DN
	#define KEY_LH_C5R3 B
	#define KEY_LH_C4R3 Y
	#define KEY_LH_C3R3 O
	#define KEY_LH_C2R3 U
	#define KEY_LH_C1R3 SEMI
	#define KEY_RH_C1R3 X
	#define KEY_RH_C2R3 L
	#define KEY_RH_C3R3 D
	#define KEY_RH_C4R3 W
	#define KEY_RH_C5R3 V
	#define KEY_RH_C6R3 DOWN
	#define KEY_LH_C6R4 Z
	#define KEY_LH_C5R4 C
	#define KEY_LH_C4R4 I
	#define KEY_LH_C3R4 E
	#define KEY_LH_C2R4 A
	#define KEY_LH_C1R4 COMMA
	#define KEY_RH_C1R4 K
	#define KEY_RH_C2R4 H
	#define KEY_RH_C3R4 T
	#define KEY_RH_C4R4 N
	#define KEY_RH_C5R4 S
	#define KEY_RH_C6R4 Q
	#define KEY_LH_C6R5 LSFT
	#define KEY_LH_C5R5 SQT
	#define KEY_LH_C4R5 MINUS
	#define KEY_LH_C3R5 EQUAL
	#define KEY_LH_C2R5 DOT
	#define KEY_LH_C1R5 FSLH
	#define KEY_LH_T1 ESC
	#define KEY_LH_T2 INSERT
	#define KEY_LH_T3 0
	#define KEY_RH_T3 0
	#define KEY_RH_T2 DELETE
	#define KEY_RH_T1 ENTER
	#define KEY_RH_C1R5 J
	#define KEY_RH_C2R5 M
	#define KEY_RH_C3R5 G
	#define KEY_RH_C4R5 P
	#define KEY_RH_C5R5 F
	#define KEY_RH_C6R5 RSFT
	#define KEY_LH_C6R6 0
	#define KEY_LH_C5R6 GRAVE
	#define KEY_LH_C4R6 LBKT
	#define KEY_LH_C3R6 RBKT
	#define KEY_LH_C2R6 LSFT
	#define KEY_LH_T4 SPACE
	#define KEY_LH_T5 TAB
	#define KEY_LH_T6 0
	#define KEY_RH_T6 0
	#define KEY_RH_T5 BACKSPACE
	#define KEY_RH_T4 R
	#define KEY_RH_C2R6 RSFT
	#define KEY_RH_C3R6 LPAR
	#define KEY_RH_C4R6 RPAR
	#define KEY_RH_C5R6 BSLH
	#define KEY_RH_C6R6 0
#endif
#if defined(LAYER_Engrammer) && LAYER_Engrammer == 0
	#define KEY_LH_C6R1 UP
	#define KEY_LH_C5R1 DOWN
	#define KEY_LH_C4R1 A
	#define KEY_LH_C3R1 B
	#define KEY_LH_C2R1 C
	#define KEY_RH_C2R1 D
	#define KEY_RH_C3R1 E
	#define KEY_RH_C4R1 F
	#define KEY_RH_C5R1 LEFT
	#define KEY_RH_C6R1 RIGHT
	#define KEY_LH_C6R2 EQUAL
	#define KEY_LH_C5R2 N1
	#define KEY_LH_C4R2 N2
	#define KEY_LH_C3R2 N3
	#define KEY_LH_C2R2 N4
	#define KEY_LH_C1R2 N5
	#define KEY_RH_C1R2 N6
	#define KEY_RH_C2R2 N7
	#define KEY_RH_C3R2 N8
	#define KEY_RH_C4R2 N9
	#define KEY_RH_C5R2 N0
	#define KEY_RH_C6R2 BSLH
	#define KEY_LH_C6R3 GRAVE
	#define KEY_LH_C5R3 B
	#define KEY_LH_C4R3 Y
	#define KEY_LH_C3R3 O
	#define KEY_LH_C2R3 U
	#define KEY_LH_C1R3 SQT
	#define KEY_RH_C1R3 SEMI
	#define KEY_RH_C2R3 L
	#define KEY_RH_C3R3 D
	#define KEY_RH_C4R3 W
	#define KEY_RH_C5R3 V
	#define KEY_RH_C6R3 Z
	#define KEY_LH_C6R4 Z
	#define KEY_LH_C5R4 C
	#define KEY_LH_C4R4 I
	#define KEY_LH_C3R4 E
	#define KEY_LH_C2R4 A
	#define KEY_LH_C1R4 COMMA
	#define KEY_RH_C1R4 DOT
	#define KEY_RH_C2R4 H
	#define KEY_RH_C3R4 T
	#define KEY_RH_C4R4 S
	#define KEY_RH_C5R4 N
	#define KEY_RH_C6R4 Q
	#define KEY_LH_C6R5 LSFT
	#define KEY_LH_C5R5 G
	#define KEY_LH_C4R5 X
	#define KEY_LH_C3R5 J
	#define KEY_LH_C2R5 K
	#define KEY_LH_C1R5 MINUS
	#define KEY_LH_T1 ESC
	#define KEY_LH_T2 K_APP
	#define KEY_LH_T3 0
	#define KEY_RH_T3 0
	#define KEY_RH_T2 INSERT
	#define KEY_RH_T1 ENTER
	#define KEY_RH_C1R5 FSLH
	#define KEY_RH_C2R5 R
	#define KEY_RH_C3R5 M
	#define KEY_RH_C4R5 F
	#define KEY_RH_C5R5 P
	#define KEY_RH_C6R5 RSFT
	#define KEY_LH_C6R6 0
	#define KEY_LH_C5R6 GRAVE
	#define KEY_LH_C4R6 LBKT
	#define KEY_LH_C3R6 RBKT
	#define KEY_LH_C2R6 LSFT
	#define KEY_LH_T4 BACKSPACE
	#define KEY_LH_T5 DELETE
	#define KEY_LH_T6 0
	#define KEY_RH_T6 0
	#define KEY_RH_T5 TAB
	#define KEY_RH_T4 SPACE
	#define KEY_RH_C2R6 RSFT
	#define KEY_RH_C3R6 LPAR
	#define KEY_RH_C4R6 RPAR
	#define KEY_RH_C5R6 BSLH
	#define KEY_RH_C6R6 0
#endif
#if defined(LAYER_Engram) && LAYER_Engram == 0
	#define KEY_LH_C6R1 UP
	#define KEY_LH_C5R1 DOWN
	#define KEY_LH_C4R1 A
	#define KEY_LH_C3R1 B
	#define KEY_LH_C2R1 C
	#define KEY_RH_C2R1 D
	#define KEY_RH_C3R1 E
	#define KEY_RH_C4R1 F
	#define KEY_RH_C5R1 LEFT
	#define KEY_RH_C6R1 RIGHT
	#define KEY_LH_C6R2 LBKT
	#define KEY_LH_C5R2 N1
	#define KEY_LH_C4R2 N2
	#define KEY_LH_C3R2 N3
	#define KEY_LH_C2R2 N4
	#define KEY_LH_C1R2 N5
	#define KEY_RH_C1R2 N6
	#define KEY_RH_C2R2 N7
	#define KEY_RH_C3R2 N8
	#define KEY_RH_C4R2 N9
	#define KEY_RH_C5R2 N0
	#define KEY_RH_C6R2 RBKT
	#define KEY_LH_C6R3 HASH
	#define KEY_LH_C5R3 B
	#define KEY_LH_C4R3 Y
	#define KEY_LH_C3R3 O
	#define KEY_LH_C2R3 U
	#define KEY_LH_C1R3 SQT
	#define KEY_RH_C1R3 DQT
	#define KEY_RH_C2R3 L
	#define KEY_RH_C3R3 D
	#define KEY_RH_C4R3 W
	#define KEY_RH_C5R3 V
	#define KEY_RH_C6R3 Z
	#define KEY_LH_C6R4 Z
	#define KEY_LH_C5R4 C
	#define KEY_LH_C4R4 I
	#define KEY_LH_C3R4 E
	#define KEY_LH_C2R4 A
	#define KEY_LH_C1R4 COMMA
	#define KEY_RH_C1R4 DOT
	#define KEY_RH_C2R4 H
	#define KEY_RH_C3R4 T
	#define KEY_RH_C4R4 S
	#define KEY_RH_C5R4 N
	#define KEY_RH_C6R4 Q
	#define KEY_LH_C6R5 LSFT
	#define KEY_LH_C5R5 G
	#define KEY_LH_C4R5 X
	#define KEY_LH_C3R5 J
	#define KEY_LH_C2R5 K
	#define KEY_LH_C1R5 MINUS
	#define KEY_LH_T1 ESC
	#define KEY_LH_T2 K_APP
	#define KEY_LH_T3 0
	#define KEY_RH_T3 0
	#define KEY_RH_T2 INSERT
	#define KEY_RH_T1 ENTER
	#define KEY_RH_C1R5 QMARK
	#define KEY_RH_C2R5 R
	#define KEY_RH_C3R5 M
	#define KEY_RH_C4R5 F
	#define KEY_RH_C5R5 P
	#define KEY_RH_C6R5 RSFT
	#define KEY_LH_C6R6 0
	#define KEY_LH_C5R6 AT
	#define KEY_LH_C4R6 LBKT
	#define KEY_LH_C3R6 RBKT
	#define KEY_LH_C2R6 LSFT
	#define KEY_LH_T4 BACKSPACE
	#define KEY_LH_T5 DELETE
	#define KEY_LH_T6 0
	#define KEY_RH_T6 0
	#define KEY_RH_T5 TAB
	#define KEY_RH_T4 SPACE
	#define KEY_RH_C2R6 RSFT
	#define KEY_RH_C3R6 LPAR
	#define KEY_RH_C4R6 RPAR
	#define KEY_RH_C5R6 FSLH
	#define KEY_RH_C6R6 0
#endif
#if defined(LAYER_Dvorak) && LAYER_Dvorak == 0
	#define KEY_LH_C6R1 UP
	#define KEY_LH_C5R1 DOWN
	#define KEY_LH_C4R1 A
	#define KEY_LH_C3R1 B
	#define KEY_LH_C2R1 C
	#define KEY_RH_C2R1 D
	#define KEY_RH_C3R1 E
	#define KEY_RH_C4R1 F
	#define KEY_RH_C5R1 LEFT
	#define KEY_RH_C6R1 RIGHT
	#define KEY_LH_C6R2 EQUAL
	#define KEY_LH_C5R2 N1
	#define KEY_LH_C4R2 N2
	#define KEY_LH_C3R2 N3
	#define KEY_LH_C2R2 N4
	#define KEY_LH_C1R2 N5
	#define KEY_RH_C1R2 N6
	#define KEY_RH_C2R2 N7
	#define KEY_RH_C3R2 N8
	#define KEY_RH_C4R2 N9
	#define KEY_RH_C5R2 N0
	#define KEY_RH_C6R2 BSLH
	#define KEY_LH_C6R3 TAB
	#define KEY_LH_C5R3 SQT
	#define KEY_LH_C4R3 COMMA
	#define KEY_LH_C3R3 DOT
	#define KEY_LH_C2R3 P
	#define KEY_LH_C1R3 Y
	#define KEY_RH_C1R3 F
	#define KEY_RH_C2R3 G
	#define KEY_RH_C3R3 C
	#define KEY_RH_C4R3 R
	#define KEY_RH_C5R3 L
	#define KEY_RH_C6R3 SLASH
	#define KEY_LH_C6R4 CAPS
	#define KEY_LH_C5R4 A
	#define KEY_LH_C4R4 O
	#define KEY_LH_C3R4 E
	#define KEY_LH_C2R4 U
	#define KEY_LH_C1R4 I
	#define KEY_RH_C1R4 D
	#define KEY_RH_C2R4 H
	#define KEY_RH_C3R4 T
	#define KEY_RH_C4R4 N
	#define KEY_RH_C5R4 S
	#define KEY_RH_C6R4 MINUS
	#define KEY_LH_C6R5 LSFT
	#define KEY_LH_C5R5 SEMI
	#define KEY_LH_C4R5 Q
	#define KEY_LH_C3R5 J
	#define KEY_LH_C2R5 K
	#define KEY_LH_C1R5 X
	#define KEY_LH_T1 ESC
	#define KEY_LH_T2 K_APP
	#define KEY_LH_T3 0
	#define KEY_RH_T3 0
	#define KEY_RH_T2 INSERT
	#define KEY_RH_T1 ENTER
	#define KEY_RH_C1R5 B
	#define KEY_RH_C2R5 M
	#define KEY_RH_C3R5 W
	#define KEY_RH_C4R5 V
	#define KEY_RH_C5R5 Z
	#define KEY_RH_C6R5 RSFT
	#define KEY_LH_C6R6 0
	#define KEY_LH_C5R6 GRAVE
	#define KEY_LH_C4R6 LBKT
	#define KEY_LH_C3R6 RBKT
	#define KEY_LH_C2R6 LSFT
	#define KEY_LH_T4 BACKSPACE
	#define KEY_LH_T5 DELETE
	#define KEY_LH_T6 0
	#define KEY_RH_T6 0
	#define KEY_RH_T5 TAB
	#define KEY_RH_T4 SPACE
	#define KEY_RH_C2R6 RSFT
	#define KEY_RH_C3R6 LPAR
	#define KEY_RH_C4R6 RPAR
	#define KEY_RH_C5R6 BSLH
	#define KEY_RH_C6R6 0
#endif
#if defined(LAYER_Colemak) && LAYER_Colemak == 0
	#define KEY_LH_C6R1 UP
	#define KEY_LH_C5R1 DOWN
	#define KEY_LH_C4R1 A
	#define KEY_LH_C3R1 B
	#define KEY_LH_C2R1 C
	#define KEY_RH_C2R1 D
	#define KEY_RH_C3R1 E
	#define KEY_RH_C4R1 F
	#define KEY_RH_C5R1 LEFT
	#define KEY_RH_C6R1 RIGHT
	#define KEY_LH_C6R2 EQUAL
	#define KEY_LH_C5R2 N1
	#define KEY_LH_C4R2 N2
	#define KEY_LH_C3R2 N3
	#define KEY_LH_C2R2 N4
	#define KEY_LH_C1R2 N5
	#define KEY_RH_C1R2 N6
	#define KEY_RH_C2R2 N7
	#define KEY_RH_C3R2 N8
	#define KEY_RH_C4R2 N9
	#define KEY_RH_C5R2 N0
	#define KEY_RH_C6R2 BSLH
	#define KEY_LH_C6R3 GRAVE
	#define KEY_LH_C5R3 Q
	#define KEY_LH_C4R3 W
	#define KEY_LH_C3R3 F
	#define KEY_LH_C2R3 P
	#define KEY_LH_C1R3 G
	#define KEY_RH_C1R3 J
	#define KEY_RH_C2R3 L
	#define KEY_RH_C3R3 U
	#define KEY_RH_C4R3 Y
	#define KEY_RH_C5R3 SEMI
	#define KEY_RH_C6R3 MINUS
	#define KEY_LH_C6R4 CAPS
	#define KEY_LH_C5R4 A
	#define KEY_LH_C4R4 R
	#define KEY_LH_C3R4 S
	#define KEY_LH_C2R4 T
	#define KEY_LH_C1R4 D
	#define KEY_RH_C1R4 H
	#define KEY_RH_C2R4 N
	#define KEY_RH_C3R4 E
	#define KEY_RH_C4R4 I
	#define KEY_RH_C5R4 O
	#define KEY_RH_C6R4 SQT
	#define KEY_LH_C6R5 LSFT
	#define KEY_LH_C5R5 Z
	#define KEY_LH_C4R5 X
	#define KEY_LH_C3R5 C
	#define KEY_LH_C2R5 V
	#define KEY_LH_C1R5 B
	#define KEY_LH_T1 ESC
	#define KEY_LH_T2 K_APP
	#define KEY_LH_T3 0
	#define KEY_RH_T3 0
	#define KEY_RH_T2 INSERT
	#define KEY_RH_T1 ENTER
	#define KEY_RH_C1R5 K
	#define KEY_RH_C2R5 M
	#define KEY_RH_C3R5 COMMA
	#define KEY_RH_C4R5 DOT
	#define KEY_RH_C5R5 FSLH
	#define KEY_RH_C6R5 RSFT
	#define KEY_LH_C6R6 0
	#define KEY_LH_C5R6 GRAVE
	#define KEY_LH_C4R6 LBKT
	#define KEY_LH_C3R6 RBKT
	#define KEY_LH_C2R6 LSFT
	#define KEY_LH_T4 BACKSPACE
	#define KEY_LH_T5 DELETE
	#define KEY_LH_T6 0
	#define KEY_RH_T6 0
	#define KEY_RH_T5 TAB
	#define KEY_RH_T4 SPACE
	#define KEY_RH_C2R6 RSFT
	#define KEY_RH_C3R6 LPAR
	#define KEY_RH_C4R6 RPAR
	#define KEY_RH_C5R6 BSLH
	#define KEY_RH_C6R6 0
#endif
#if defined(LAYER_QWERTY) && LAYER_QWERTY == 0
	#define KEY_LH_C6R1 UP
	#define KEY_LH_C5R1 DOWN
	#define KEY_LH_C4R1 A
	#define KEY_LH_C3R1 B
	#define KEY_LH_C2R1 C
	#define KEY_RH_C2R1 D
	#define KEY_RH_C3R1 E
	#define KEY_RH_C4R1 F
	#define KEY_RH_C5R1 LEFT
	#define KEY_RH_C6R1 RIGHT
	#define KEY_LH_C6R2 EQUAL
	#define KEY_LH_C5R2 N1
	#define KEY_LH_C4R2 N2
	#define KEY_LH_C3R2 N3
	#define KEY_LH_C2R2 N4
	#define KEY_LH_C1R2 N5
	#define KEY_RH_C1R2 N6
	#define KEY_RH_C2R2 N7
	#define KEY_RH_C3R2 N8
	#define KEY_RH_C4R2 N9
	#define KEY_RH_C5R2 N0
	#define KEY_RH_C6R2 MINUS
	#define KEY_LH_C6R3 TAB
	#define KEY_LH_C5R3 Q
	#define KEY_LH_C4R3 W
	#define KEY_LH_C3R3 E
	#define KEY_LH_C2R3 R
	#define KEY_LH_C1R3 T
	#define KEY_RH_C1R3 Y
	#define KEY_RH_C2R3 U
	#define KEY_RH_C3R3 I
	#define KEY_RH_C4R3 O
	#define KEY_RH_C5R3 P
	#define KEY_RH_C6R3 BSLH
	#define KEY_LH_C6R4 CAPS
	#define KEY_LH_C5R4 A
	#define KEY_LH_C4R4 S
	#define KEY_LH_C3R4 D
	#define KEY_LH_C2R4 F
	#define KEY_LH_C1R4 G
	#define KEY_RH_C1R4 H
	#define KEY_RH_C2R4 J
	#define KEY_RH_C3R4 K
	#define KEY_RH_C4R4 L
	#define KEY_RH_C5R4 SEMI
	#define KEY_RH_C6R4 SQT
	#define KEY_LH_C6R5 LSFT
	#define KEY_LH_C5R5 Z
	#define KEY_LH_C4R5 X
	#define KEY_LH_C3R5 C
	#define KEY_LH_C2R5 V
	#define KEY_LH_C1R5 B
	#define KEY_LH_T1 ESC
	#define KEY_LH_T2 K_APP
	#define KEY_LH_T3 0
	#define KEY_RH_T3 0
	#define KEY_RH_T2 INSERT
	#define KEY_RH_T1 ENTER
	#define KEY_RH_C1R5 N
	#define KEY_RH_C2R5 M
	#define KEY_RH_C3R5 COMMA
	#define KEY_RH_C4R5 DOT
	#define KEY_RH_C5R5 FSLH
	#define KEY_RH_C6R5 RSFT
	#define KEY_LH_C6R6 0
	#define KEY_LH_C5R6 GRAVE
	#define KEY_LH_C4R6 LBKT
	#define KEY_LH_C3R6 RBKT
	#define KEY_LH_C2R6 LSFT
	#define KEY_LH_T4 BACKSPACE
	#define KEY_LH_T5 DELETE
	#define KEY_LH_T6 0
	#define KEY_RH_T6 0
	#define KEY_RH_T5 TAB
	#define KEY_RH_T4 SPACE
	#define KEY_RH_C2R6 RSFT
	#define KEY_RH_C3R6 LPAR
	#define KEY_RH_C4R6 RPAR
	#define KEY_RH_C5R6 BSLH
	#define KEY_RH_C6R6 0
#endif
#if defined(LAYER_ColemakDH) && LAYER_ColemakDH == 0
	#define KEY_LH_C6R1 UP
	#define KEY_LH_C5R1 DOWN
	#define KEY_LH_C4R1 A
	#define KEY_LH_C3R1 B
	#define KEY_LH_C2R1 C
	#define KEY_RH_C2R1 D
	#define KEY_RH_C3R1 E
	#define KEY_RH_C4R1 F
	#define KEY_RH_C5R1 LEFT
	#define KEY_RH_C6R1 RIGHT
	#define KEY_LH_C6R2 EQUAL
	#define KEY_LH_C5R2 N1
	#define KEY_LH_C4R2 N2
	#define KEY_LH_C3R2 N3
	#define KEY_LH_C2R2 N4
	#define KEY_LH_C1R2 N5
	#define KEY_RH_C1R2 N6
	#define KEY_RH_C2R2 N7
	#define KEY_RH_C3R2 N8
	#define KEY_RH_C4R2 N9
	#define KEY_RH_C5R2 N0
	#define KEY_RH_C6R2 MINUS
	#define KEY_LH_C6R3 TAB
	#define KEY_LH_C5R3 Q
	#define KEY_LH_C4R3 W
	#define KEY_LH_C3R3 F
	#define KEY_LH_C2R3 P
	#define KEY_LH_C1R3 B
	#define KEY_RH_C1R3 J
	#define KEY_RH_C2R3 L
	#define KEY_RH_C3R3 U
	#define KEY_RH_C4R3 Y
	#define KEY_RH_C5R3 SEMI
	#define KEY_RH_C6R3 BSLH
	#define KEY_LH_C6R4 CAPS
	#define KEY_LH_C5R4 A
	#define KEY_LH_C4R4 R
	#define KEY_LH_C3R4 S
	#define KEY_LH_C2R4 T
	#define KEY_LH_C1R4 G
	#define KEY_RH_C1R4 M
	#define KEY_RH_C2R4 N
	#define KEY_RH_C3R4 E
	#define KEY_RH_C4R4 I
	#define KEY_RH_C5R4 O
	#define KEY_RH_C6R4 SQT
	#define KEY_LH_C6R5 LSFT
	#define KEY_LH_C5R5 Z
	#define KEY_LH_C4R5 X
	#define KEY_LH_C3R5 C
	#define KEY_LH_C2R5 D
	#define KEY_LH_C1R5 V
	#define KEY_LH_T1 ESC
	#define KEY_LH_T2 K_APP
	#define KEY_LH_T3 0
	#define KEY_RH_T3 0
	#define KEY_RH_T2 INSERT
	#define KEY_RH_T1 ENTER
	#define KEY_RH_C1R5 K
	#define KEY_RH_C2R5 H
	#define KEY_RH_C3R5 COMMA
	#define KEY_RH_C4R5 DOT
	#define KEY_RH_C5R5 FSLH
	#define KEY_RH_C6R5 RSFT
	#define KEY_LH_C6R6 0
	#define KEY_LH_C5R6 GRAVE
	#define KEY_LH_C4R6 LBKT
	#define KEY_LH_C3R6 RBKT
	#define KEY_LH_C2R6 LSFT
	#define KEY_LH_T4 BACKSPACE
	#define KEY_LH_T5 DELETE
	#define KEY_LH_T6 0
	#define KEY_RH_T6 0
	#define KEY_RH_T5 TAB
	#define KEY_RH_T4 SPACE
	#define KEY_RH_C2R6 RSFT
	#define KEY_RH_C3R6 LPAR
	#define KEY_RH_C4R6 RPAR
	#define KEY_RH_C5R6 BSLH
	#define KEY_RH_C6R6 0
#endif
