manifest:
  remotes:
    - name: moergo-sc
      url-base: https://github.com/moergo-sc
    - name: darknao
      url-base: https://github.com/darknao
    - name: qnlbnsl
      url-base: https://github.com/qnlbnsl

  projects:
    - name: zmk
      remote: qnlbnsl
      # revision: rgb-layer-24.12 #main
      revision: rgb-layer-25.04
      import: app/west.yml

    - name: prospector-zmk-module
      remote: qnlbnsl
      revision: main

  self:
    path: config
