manifest:
  remotes:
    - name: moergo-sc
    #   url-base: https://github.com/moergo-sc
    # - name: rgb-leds
      url-base: https://github.com/darknao
      
    - name: carrefinho                            # <--- add this
      url-base: https://github.com/carrefinho     # <--- and this
  projects:
    - name: zmk
      remote: moergo-sc
      revision: rgb-layer-25.04 #main
      import: app/west.yml

    - name: prospector-zmk-module                 # <--- and these
      remote: carrefinho                          # <---
      revision: main                              # <---

  self:
    path: config
