manifest:
  remotes:
    - name: moergo-sc
      url-base: https://github.com/moergo-sc
    - name: darknao
      url-base: https://github.com/darknao
    - name: qnlbnsl
      url-base: https://github.com/qnlbnsl

    - name: carrefinho                            # <--- add this
      url-base: https://github.com/carrefinho     # <--- and this
  projects:
    - name: zmk
      remote: qnlbnsl
      revision: rgb-layer-24.12 #main
      import: app/west.yml

    - name: prospector-zmk-module                 # <--- and these
      remote: carrefinho                          # <---
      revision: main                              # <---

  self:
    path: config
